package ui

// Text constants the screens compose by name; grep stays the only way a string moves.
const (
	TextMenuInstall      = "Install"
	TextMenuAssignModels = "Assign models"
	TextMenuCheckDrift   = "Check for drift"
	TextMenuUninstall    = "Uninstall"
	TextMenuDiagnostics  = "Diagnostics"
	TextMenuConfigure    = "Configure installation"
	TextMenuQuit         = "Quit"

	TextMenuInstallDesc      = "Agents, skills and MCP servers on OpenCode v2"
	TextMenuConfigureDesc    = "Change components or reapply Takt's files"
	TextMenuAssignModelsDesc = "Choose the model each agent runs on"
	TextMenuCheckDriftDesc   = "Find and restore files changed outside Takt"
	TextMenuUninstallDesc    = "Remove Takt's files, keeping what you choose"
	TextMenuDiagnosticsDesc  = "Check that each capability works"
	TextMenuQuitDesc         = "Leave Takt"

	TextGuardKeepEditing   = "Keep editing"
	TextGuardDiscard       = "Discard changes"
	TextGuardDiscardBody   = "Leaving now discards the edits you have not applied."
	TextGuardUnappliedWord = "Unapplied changes"

	// TextBrand is the wordmark shown in the shell header.
	TextBrand = "Takt AI"
	// TextShellTooSmallFmt names the minimum size, the current size and the fix.
	TextShellTooSmallFmt = "Terminal too small: need at least %dx%d (current %dx%d). Resize to continue."

	// TextCancelRequested is the footer suffix shown while a cancellation is pending.
	TextCancelRequested  = "stopping after the current phase"
	TextActionCancel     = "Cancel"
	TextEarlierPhasesFmt = "%d earlier phases done"
	TextUnavailableIntro = "Unavailable: "

	TextActionBackToMenu      = "Back to menu"
	TextActionRepair          = "Repair"
	TextActionQuit            = "Quit"
	TextActionPersonalize     = "Personalize"
	TextActionInstall         = "Install"
	TextActionApplyChanges    = "Apply changes"
	TextActionRetry           = "Retry"
	TextActionReviewAgain     = "Review again"
	TextActionKeepCurrent     = "Keep current state"
	TextActionAssignModels    = TextMenuAssignModels
	TextActionBack            = "Back"
	TextActionUninstall       = "Uninstall"
	TextActionSelectFiles     = "Select files to restore"
	TextActionRestoreSelected = "Restore selected files"
	TextActionReselect        = "Back to selection"
	TextActionRescan          = "Check again"
	TextActionAssignAnother   = "Assign another"

	// TextOpenCodeNotFound keeps the install going when the harness binary is
	// absent: the configuration deploys so a later install works.
	TextOpenCodeNotFound    = "OpenCode was not found on PATH — Takt installs its configuration anyway."
	TextTitleInstall        = "Install"
	TextTitleConfigure      = "Configure installation"
	TextStepComponents      = "Components"
	TextStepExisting        = "Existing files"
	TextStepReview          = "Review"
	TextStepResult          = "Result"
	TextStepInstalling      = "Installing"
	TextStepApplying        = "Applying"
	TextBusyInstallation    = "Installation"
	TextBusyConfiguration   = "Configuration"
	TextComponentsIntro     = "Choose what to include. Takt agents and core skills are always installed."
	TextConflictPreexisting = "pre-existing, not created by Takt"
	TextConflictEdited      = "edited after installation"
	TextConflictMissing     = "missing, deleted after installation"
	TextConflictsIntro      = "These files differ from what Takt would write. Choose what to do with each one; nothing changes until you apply the review."
	TextConflictSource      = "  Source: "
	TextConflictAffects     = "  Affects: "
	TextConflictKnown       = "  Known incompatibility: "
	TextConflictAlternative = "  Alternative: "
	TextConflictUncertain   = "  Uncertain: "
	TextConflictRecommend   = "  Recommended: restore Takt version."
	TextKeepMine            = "Keep my version"
	TextRestoreTakt         = "Restore Takt version"
	TextPreviouslyKeptTitle = "Previously kept — no new consequences"
	TextNotAffectedTitle    = "Not affected by this operation"
	TextKeepCannotWorkFmt   = "Keeping %s cannot work. %s"
	TextScopeFmt            = "Scope: %s · user-global installation"
	TextCannotPrepareIntro  = "Cannot prepare the review: "
	TextNothingChangedRetry = "Nothing was changed. Personalize your choices, or go back and try again."
	TextReplacesYours       = " (replaces your version)"
	TextYourVersionKept     = " (your version is kept)"
	TextNotAffectedNote     = " (not affected by this operation)"
	TextPreviouslyKeptNote  = " (previously kept)"
	TextNothingToChange     = "Nothing to change: installed files already match these choices."
	TextRemovalFmt          = "%s — %s"

	// Review: a title, then what the install sets up and what it changes on disk.
	TextReviewInstallTitle  = "Install into ~/.config/opencode"
	TextReviewApplyTitle    = "Apply to ~/.config/opencode"
	TextReviewScope         = "for every project"
	TextGroupInstalls       = "WHAT YOU GET"
	TextGroupDisk           = "WHAT CHANGES ON DISK"
	TextAgentOne            = "agent"
	TextAgentMany           = "agents"
	TextSkillOne            = "skill"
	TextSkillMany           = "skills"
	TextMCPServerOne        = "MCP server"
	TextMCPServerMany       = "MCP servers"
	TextIntegrationOne      = "integration"
	TextIntegrationMany     = "integrations"
	TextNewFileOne          = "new file"
	TextNewFileMany         = "new files"
	TextUpdatedCountFmt     = "%d updated"
	TextAgentRolesFmt       = "%d orchestrator · %d specialists"
	TextAgentModelsAllFmt   = "on %s"
	TextAgentModelsFmt      = "%d on %s"
	TextInheritedModel      = "OpenCode's default model"
	TextConfigMerged        = "merged — your settings are kept"
	TextConfigUpdated       = "updated"
	TextFieldKept           = "Kept"
	TextFieldNotInstalled   = "Not installed"
	TextFieldUncertain      = "Uncertain"
	TextListSeparator       = " · "
	TextRetryInstall        = "Review the error, then retry the installation."
	TextRetryApply          = "Review the error, then retry applying the changes."
	TextReviewAgainNote     = "Review again checks the actual files first, then applies what is still missing."
	TextInstalledForFmt     = "Takt AI is installed in %s."
	TextUpdatedForFmt       = "Takt AI is updated in %s."
	TextFilesChangedFmt     = "Files: %d changed, %d unchanged"
	TextPreservedFmt        = ", %d preserved"
	TextIncompleteWorkTitle = "Incomplete work"
	TextIncompleteWorkIntro = "The installation completed with optional work still pending."
	TextNotReady            = "Not ready to work: some capabilities failed their check."
	TextUnconfirmed         = "Some checks could not run, so those capabilities are unconfirmed, not failed."
	TextCannotGuaranteeFmt  = "Takt cannot guarantee %s while your versions are kept."
	TextUseDrift            = "Use Check for drift from the menu to restore these files later."
	TextTakeEffectFmt       = "Changes take effect the next time you start %s."

	TextUninstallModifiedTitle = "Uninstall · Modified files"
	// TextUninstallEngramTitle precedes the retention choice: the Engram data
	// lives outside the Takt footprint, so uninstall asks explicitly.
	TextUninstallEngramTitle   = "Uninstall · Engram database"
	TextUninstallReviewTitle   = "Uninstall · Review"
	TextUninstallResultTitle   = "Uninstall · Result"
	TextUninstallTitle         = "Uninstall"
	TextUninstallBusy          = "Uninstall"
	TextUninstallCannotPlan    = "Could not prepare the uninstall plan: "
	TextUninstallModifiedIntro = "These files were installed by Takt and changed since. Choose what to do with each one."
	TextUninstallRemoveOpt     = "Remove"
	TextUninstallKeptMoveIntro = "Kept files move to "
	TextUninstallKeptMoveOutro = " so they are not left inside the removed installation."
	TextEngramQuestion         = "Engram database (outside Takt footprint):"
	TextEngramLeave            = "Leave"
	TextEngramRetain           = "Retain"
	TextEngramRemove           = "Remove"
	TextEngramNever            = "Leave keeps it where it is. Retain also copies it to the retained directory. Only Remove asks to discard it."
	TextUninstallRemoveFmt     = "Remove: %s installed by Takt"
	TextUninstallMemoryLine    = "  Memory server (Engram) entries in each harness configuration"
	TextUninstallRestoreTitle  = "Restore to their content from before Takt was installed:"
	TextUninstallKeepInPlace   = "Keep in place:"
	TextUninstallKeepMine      = "Keep my version:"
	TextUninstallRetainedData  = "Retained data: "
	TextUninstallNoBackup      = "Takt keeps no backup of removed files."
	TextUninstallEngramChose   = "You chose to remove the Engram database: its configuration is removed, and anything without a supported remover is reported as incomplete."
	TextUninstallEngramRetains = "You chose to retain the Engram database: a consistent copy is handed off to the retained directory and the original stays where it is."
	TextUninstallMemoryKept    = "Engram memory retained at: "
	TextUninstallEngramStays   = "Memories stored by Engram are not part of the installation and stay where they are."
	TextUninstallAgainNote     = "Uninstall again checks the actual files first, then removes what remains."
	TextUninstallFailedIntro   = "Uninstall did not complete: "
	TextUninstallPartialFmt    = "Takt was removed from %s, but some cleanup did not complete."
	TextUninstallOkFmt         = "Takt was removed from %s."
	TextUninstallRemovedFmt    = "Removed: %s"
	TextUninstallKeptChoice    = "Kept by your choice:"
	TextUninstallRetainedIn    = "Retained in: "
	TextUninstallIncomplete    = "Not removed (incomplete):"
	TextUninstallTakeEffectFmt = "Changes take effect the next time you start %s."
	TextOneFile                = "1 file"
	TextFilesFmt               = "%d files"
	TextReasonPreexisting      = "existed before Takt was installed"
	TextReasonAdditions        = "existed before Takt was installed, still contains settings Takt added"
	TextModifiedSuffix         = " - your modified version"
	TextReasonSep              = " - "

	TextDriftSelectTitle  = "Check for drift · Select"
	TextDriftReviewTitle  = "Check for drift · Review"
	TextDriftResultTitle  = "Check for drift · Result"
	TextDriftEmptyTitle   = "Check for drift · Nothing installed"
	TextDriftReportTitle  = "Check for drift · Report"
	TextDriftBusy         = "Drift correction"
	TextDriftChecking     = "Checking managed files..."
	TextDriftCannotCheck  = "Could not check managed files: "
	TextDriftClean        = "No drift: every managed file matches its installed definition."
	TextDriftNoVerify     = "A drift check does not verify functionality. Run Diagnostics to check functional availability."
	TextDriftDifferOutro  = " differ from their installed definition."
	TextDriftOneManaged   = "1 managed file"
	TextDriftManagedFmt   = "%d managed files"
	TextDriftSelectIntro  = "Select the files to restore to their installed definition."
	TextDriftSelectStar   = "* Select at least one file to continue."
	TextScopeSimpleFmt    = "Scope: %s"
	TextDriftRestoreHead  = "Restore:"
	TextDriftPreserveHead = "Preserve:"
	TextDriftPreserveAll  = "Every other managed file stays as it is."
	TextDriftRefFmt       = "Reference: definitions of Takt %s as installed."
	TextDriftRefUnknown   = "Reference: the installed Takt version is not recorded; this build is "
	TextDriftRefMismatch  = "Reference: installed with Takt "
	TextDriftCheckAgain   = "Check again shows which managed files still differ from their installed definition."
	TextDriftRestoredFmt  = "Restored %s, but correction did not complete: %s"
	TextDriftRestoredHead = "Restored:"
	TextDriftSeeCurrent   = "Check again to see the current state of managed files."
	TextDriftFailedIntro  = "Drift correction did not complete: "
	TextDriftPartialFmt   = "Restored %s; %d could not be planned."
	TextDriftNoPlanned    = "No selected file could be planned for restoration."
	TextDriftAlreadyMatch = "The selected files already match their installed definition."
	TextDriftRestoredOk   = "Restored "
	TextDriftRestoredOut  = " to their installed definition."
	TextDriftUnplanned    = "Could not be planned:"
	TextDriftLeftAsIs     = "No longer part of the installed definition, so it was left as it is."
	TextDriftNoFuncVerify = "Drift correction does not verify functionality. Run Diagnostics to check functional availability."
	TextDriftTakeEffect   = "Changes take effect the next time you start your harness."
	TextDriftBackupIntro  = "Restoring is not an undo of your edits; backup copies stay in "
	TextDriftRecreated    = "Recreated from the installed definition."
	TextDriftReplacedEdit = "Your edit is replaced by the installed definition; a backup copy is kept first."
	TextDriftReplacedFile = "Your file is replaced by the installed definition; a backup copy is kept first."
	TextDriftVersionBlock = "The installed version's definitions are not available in this build"

	// Models flow.
	TextModelsBusy        = "Model assignment"
	TextModelsResultTitle = "Assign models · Result"
	TextModelsTitle       = TextMenuAssignModels
	TextModelsLoadFail    = "Could not load the installed configuration: "
	TextModelsNothingKept = "Nothing was changed. Esc returns to the menu."
	TextModelsNothing     = "Nothing installed yet. Install Takt before assigning models."
	TextModelsAssignAgain = "Assign another shows the current assignments."
	TextModelsAssignFail  = "Could not assign models on "
	TextModelsFailNote    = "Specialists applied before the failure keep their new model. Assign another shows the current assignments."
	TextModelsNoChanges   = "No changes were needed."
	TextModelsTakeEffect  = "Changes take effect the next time you start "
	TextModelsTitleFmt    = "Assign models · %s"

	// Model picker.
	TextPickerInheritFmt  = "inherits %s default"
	TextPickerAllAgents   = "All agents"
	TextPickerMixed       = "different models"
	TextPickerChangedMark = "• "
	TextModelsAgentsStep  = "Agents"
	TextModelsAssignedOne = "Model assigned to 1 agent."
	TextModelsAssignedFmt = "Models assigned to %d agents."
	// TextPickerNoChanges states the picker's no-op case so the footer can
	// disable commitment without a hint of what to change.
	TextPickerNoChanges    = "No changes to apply"
	TextPickerCurrent      = "Current: "
	TextPickerLoadingFmt   = "Loading %s models."
	TextPickerLoadFailFmt  = "%s models are unavailable: %s. Agents can keep inheriting its default."
	TextPickerNotInstalled = "OpenCode is not installed"
	TextPickerNoAnswer     = "OpenCode did not respond"
	TextPickerSearchIntro  = "Search: "
	TextPickerNoMatchFmt   = "No models match %q. Ctrl+U clears the search."
	TextPickerPosFmt       = "%d / %d"
	TextScrollPosFmt       = "%d–%d / %d"

	// Diagnostics.
	TextDiagCheckingTitle = "Diagnostics · Checking"
	TextDiagReportTitle   = "Diagnostics · Capabilities"
	TextDiagBusy          = "Checking each capability…"
	// TextDiagNone covers the case where no capability check produced any
	// evidence at all, so the report stays honest instead of showing zero rows.
	TextDiagNone = "No capability could be checked."

	// Shared outcome.
	TextCancelledNone      = "Cancelled before any change was applied."
	TextOutcomeNothing     = "Nothing was changed."
	TextCancelledPartFmt   = "Cancelled after applying %d of %d changes."
	TextOutcomeAppliedHead = "Applied:"
	TextNotAppliedFmt      = "%d changes were not applied"
	TextOneNotApplied      = "1 change was not applied"
	TextAppliedStaysIntro  = "Current state: the applied changes stay in place; "
	TextNoRollback         = "Automatic rollback is not available."
	TextBackupKeptIntro    = " Backup copies of replaced files are in "
	TextLateCancel         = "Completed before the cancellation could take effect."
	TextFunctionalTitle    = "Capabilities"
	TextStateNotWorking    = " — not working"
	TextStateNotChecked    = " — not checked"
)
