{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "takt-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "takt-ai.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "takt-ai.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if kindIs "slice" .Values.networkPolicy.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - port: {{ .Values.port }}
          protocol: TCP
      {{- with .Values.networkPolicy.ingressFrom }}
      from: {{ toYaml . | nindent 8 }}
      {{- end }}
  {{- if kindIs "slice" .Values.networkPolicy.egress }}
  egress: {{ toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
