// Copyright (C) 2025 Takt AI Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

package opencode

import (
	_ "embed"
	"encoding/json"

	"github.com/rou-cru/takt-ai/takt/agents/shared"
)

// Context7RemoteURL is the canonical context7 remote MCP endpoint deployed
// into opencode.json by the context7 component.
const Context7RemoteURL = shared.Context7RemoteURL

// TaktTheme is the OpenCode theme deployed by the theme component.
const TaktTheme = "takt-kanagawa"

// context7Config returns the mcp entry for the context7 component. The map
// shape matches a deep merge of the canonical context7 overlay into
// opencode.json.
func context7Config() map[string]any {
	return map[string]any{
		"context7": map[string]any{
			"type":    "remote",
			"url":     Context7RemoteURL,
			"enabled": true,
		},
	}
}

// permissionsConfig returns the canonical OpenCode permission rules: bash and
// read are permissive by default with ask rules for state-changing Git
// commands and deny rules for secret files and credentials.
func permissionsConfig() map[string]any {
	read := map[string]any{
		"*":       "allow",
		"*.env":   "deny",
		"*.env.*": "deny",
	}
	for _, glob := range shared.SensitivePathGlobs {
		read["**/"+glob] = "deny"
	}
	return map[string]any{
		"bash": map[string]any{
			"*":                  "allow",
			"git commit *":       "ask",
			"git push *":         "ask",
			"git push":           "ask",
			"git push --force *": "ask",
			"git rebase *":       "ask",
			"git reset --hard *": "ask",
		},
		"read": read,
	}
}

//go:embed assets/takt-logo.tsx
var taktLogoPluginSource string

// TaktLogoPluginArtifact returns the local OpenCode TUI plugin that renders
// the Takt brand logo on the home screen. The asset is generated by
// cmd/generate-logo from docs/assets/brand/takt-ai-logo-source.png — do not
// hand-edit it.
func TaktLogoPluginArtifact() Artifact {
	return Artifact{
		Path:    ".config/opencode/tui-plugins/takt-logo.tsx",
		Content: []byte(taktLogoPluginSource),
	}
}

// tuiConfig is the OpenCode TUI configuration file projection. Plugin paths
// are resolved by OpenCode relative to the config file that declares them.
type tuiConfig struct {
	Schema string   `json:"$schema"`
	Plugin []string `json:"plugin"`
}

// TaktLogoRegistrationArtifact returns tui.json registering the local Takt
// logo plugin.
func TaktLogoRegistrationArtifact() Artifact {
	config := tuiConfig{
		Schema: "https://opencode.ai/tui.json",
		Plugin: []string{"./tui-plugins/takt-logo.tsx"},
	}
	content, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		// A fixed string slice cannot fail to marshal; guard so a future field
		// type change cannot deploy a truncated registration file.
		panic("marshal OpenCode tui.json: " + err.Error())
	}
	return Artifact{
		Path:    ".config/opencode/tui.json",
		Content: append(content, '\n'),
	}
}
